### ISSUE TITLE
Left at bottom of the page after submitting new booking

### ISSUE THREAD

**Issue by communityrmhc** [megandalster/rmh-homeroomcivi#57]
After I hit submit for a new booking, it defaults to the bottom of the page and you have to scroll up to see anything.

**Comment by megandalster** [comment]
This is difficult to fix.  Can you live with it?

**Comment by communityrmhc** [comment]
Yes, we if we have to :) 

Just kidding, it's fine! I wonder if it is different in different browsers.  I will try.
