### ISSUE TITLE
Info not saved when hitting back

### ISSUE THREAD

**Issue by communityrmhc** [megandalster/rmh-homeroomcivi#58]
Submitting a new booking, forgot to put in a phone number and got an error message that needed phone number.  Tried to go back and the info was lost.

**Comment by megandalster** [comment]
I cannot replicate this problem.  When I left the phone number blank and hit the back button, the info I entered was still there, so I added the phone and the booking was saved.

**Comment by communityrmhc** [comment]
Hmmm that is interesting.  I just tried it (creating a new booking for a new person) and I lost all of my data again.

**Comment by megandalster** [comment]
Gretchen, maybe we should step through this issue together when you get a minute.  Allen
