### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by communityrmhc** [megandalster/rmh-homeroomcivi#59]
Received this warning message: Warning: mktime() expects parameter 6 to be long, string given in /home/rmhport/public_html/homeroom/database/dbBookings.php on line 332

When viewing "guest" info for Mary-Jo Smith. 
![error](https://cloud.githubusercontent.com/assets/14002961/11963193/19840b64-a8b3-11e5-99fc-1a67363149e5.jpg)

**Comment by megandalster** [comment]
This happens when a booking's date-out is invalid or left blank, which is the case on a few of the older bookings.  I fixed this problem so that these older bookings do not appear on this page.
