### ISSUE TITLE
Error when editing

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#60]
When I tried to edit a guest's record to add a "do not readmit" note, I got this error and the record completely disappeared (it was for Christin Martell).  I did it twice, and got the same result twice.  

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Edge for details','York','guest','c528824cafa91c062c20f88d6a77c4e6')' at line 1 unable to insert into dbPersons: Christin2072564653 Update successful. Click edit to review your changes.

**Comment by megandalster** [comment]
I just edited Christin Martell's record and added the manager's note "do not readmit".  It seemed to work.  Take a look to be sure I didn't overlook something.
