### ISSUE TITLE
Guest list 

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#61]
I am entering past bookings (for December 2015), and the additional guests that I list in the booking aren't showing up on the room log once I've assigned the room (even if I checked the "present" button on the booking).  If I go back in to the booking to edit it, the people I typed in aren't there.  When I re-enter them and save the booking, the whole family has disappeared from the log.  But then when I re-assign the room to them, everyone shows up.  Very quirky!  If I need to take some screen shots to explain, let me know.

**Comment by gnoonan** [comment]
I just took a second look at it--it seems that the first person on the "additional guests" list doesn't get saved, but the second one does.  E.g., I just entered a booking for a family and mom and the brother are showing up on the log (even though I didn't check "present" next to the brother), but the father, who was first on the list of additional guests, isn't showing up.

**Comment by gnoonan** [comment]
So I just entered this family
![screenshot 1](https://cloud.githubusercontent.com/assets/14204120/12153937/b43ba102-b48a-11e5-9f40-8e1e2767d4cf.jpg)

**Comment by gnoonan** [comment]
But when i assign them to the room, dad doesn't show up on the log.
![image](https://cloud.githubusercontent.com/assets/14204120/12153964/e6bb1bd0-b48a-11e5-8702-ae2f4ebcb007.png)

**Comment by megandalster** [comment]
I added the father Raymundo back into the booking and checked him present, and he now shows up on the Room Log for December 4.  If I revisit the booking, he and the other guests are all still listed.  So I think the dropping of the first guest from the list happens only when creating a new booking.  Once the booking is there and we edit it, nobody seems to be getting dropped.  Let's keep an eye on this one.

**Comment by gnoonan** [comment]
Yes, this is indeed what is happening.  I enter mom as primary, dad second, and grandma third.  Mom and grandma show up on the room log.  So i click on the room, then "please go here", then "edit this booking" and add dad back in, then he shows up.  I think we're going to have a hard time keeping the log accurate if we can't find a fix for this?

**Comment by megandalster** [comment]
This is now fixed.
