### ISSUE TITLE
Beds/baths

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#65]
Just noticed that the beds/baths aren't being shown for a lot of the rooms. 
![image](https://cloud.githubusercontent.com/assets/14204120/12154887/32b67462-b490-11e5-8220-65127e3cb357.png)

**Comment by megandalster** [comment]
You can edit these in where they are missing.  For example, to add a Queen bed and bath to room 125, as well as a strobe alarm, you can select room 125 and edit "Q, strobe" into the Beds box and select "yes" for bath.  Rooms where bath does not show up should mean "there is no private bath in this room."
