### ISSUE TITLE
Multiple rooms

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#66]
I've run into an instance where one family has two rooms.  I made a booking and assigned the room to the family, then searched the family and made another new booking then tried to assign a different room to them.  it didn't work, and the family was deleted off of the first room as well.  No idea what the best way to address this is--make some sort of change that allows you to make two bookings for the same family, or have to somehow enter the family a second time (even though it will be the same patient) and put a different primary guest?

**Comment by megandalster** [comment]
Yes, this capability was originally in Homeroom.  It's called a "linked room" and it should show up on the booking form.  I need to reactivate linked rooms, but that will take a bit of work.  Maybe a couple of weeks.

**Comment by megandalster** [comment]
Linked rooms are now activated in Homeroom.  Look at the page where you edit a booking, and you will have an opportunity to add a second room for a family.  If the family has two rooms, checking them out will remove them from both rooms and mark them as "dirty".
