### ISSUE TITLE
Fire alarms

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#70]
Something we have added to the log since you began this project is the presence of additional fire notifications in each room.  Some have a strobe and some have a horn (for visually/hearing impaired).  Could we add the following:
125-strobe
126-strobe
151-horn
152-horn
223-strobe
250-horn
251-strobe
252-horn
253-horn
254-horn
255-horn

Current log sheet attached
[Guest Room Log Sheets.docx](https://github.com/megandalster/rmh-homeroomcivi/files/83339/Guest.Room.Log.Sheets.docx)

**Comment by megandalster** [comment]
I suggest you add the fire alarm info to the "Beds" info for each room that has an alarm.  For example, room 252 now shows "Q" for a queen bed.  You can change that to "Q, horn" instead.  Let me know if this is sufficient -- a more detailed fix would be difficult for me.
