### ISSUE TITLE
Submitted by

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#72]
Is there any way to make "submitted by" a drop down that includes social workers?  It would be nice to skip the step of continually typing in the same names and phone numbers over and over.  Or at least have that field come up as blank?  Because if it autofills with the name of the person adding the booking (as it does now), I think people will often forget to change it to the name of the social worker.

**Comment by megandalster** [comment]
"Submitted By" is now a blank box where you can enter the name and phone of the social worker who submitted the referral, or else your own if there's no social worker submitting.
