### ISSUE TITLE
Can't check family out

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#73]
I'm on January 1st and would like to check the family out of 125, but there is no dropdown there that will allow me to do so.  
![image](https://cloud.githubusercontent.com/assets/14204120/13298326/59841424-db04-11e5-8565-c5f6c70e6097.png)

**Comment by gnoonan** [comment]
Something similar just happened.  I checked someone out of 245, then after I made another change to the log (checking someone in to 250), then reappeared on the log.  when I went to check them out again, the dropdown isn't there.  
![image](https://cloud.githubusercontent.com/assets/14204120/13298978/026bacbc-db07-11e5-81cc-ffce280eb4a4.png)

**Comment by gnoonan** [comment]
And now I checked a family out of 254, and when I went back to the log an entirely different family was checked in to the room?  And I can't check them out.

**Comment by gnoonan** [comment]
The issue with rooms 125 and 245 resolved itself (or you fixed it!) but now I'm on February 26th and can't check the families out of rooms 151 and 152.  Same issue, no dropdown that allows me to change the status of the room.

**Comment by megandalster** [comment]
fixed.
