### ISSUE TITLE
Checked as present

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmh-homeroomcivi#74]
This is related to the guest list issue but separate.  People on the booking show up on the log whether they are checked as "present" or not. For instance, mom just went home and dad is the only one who stayed, but they are both on the log even if I uncheck them.

**Comment by gnoonan** [comment]
And if I go into the booking to try to change who is listed as present, the whole family disappears from the log.

**Comment by megandalster** [comment]
fixed.  Now the room log shows all guests (present or absent), and clicking on a room shows only those guests who are present.  To change the status of a guest, first view the booking and then edit the booking and check/uncheck the "Present" box, and finally hit "Submit" at the bottom.
